theme: jekyll-theme-cayman
title: "Tidy Tables: Generating Scenes Using Geometric and Semantic Preferences"
description: "Summer Research Program 2020-2021, Monash University Department of Electrical and Computer Systems Engineering"
